spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_POST:5000}/${DB_NAME:cafe_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:2305}
    driverClassName: ${DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: trues
        default_schema: ${DEFAULT_SCHEMA:public}
    hibernate:
      ddl-auto: update
    show_sql: ${JPA_SHOW_SQL:true}
